### PR TITLE
add `shared_fs_path` configuration setting

### PR DESCRIPTION
**Pull request by boegel**
~WIP because I'm still testing whether this works as expected, see also companion PR https://github.com/EESSI/software-layer/pull/337~

Works as expected, testing along with https://github.com/EESSI/software-layer/pull/337 via https://github.com/boegel/software-layer/pull/27

### CODE REVIEW

**Comment by boegel** [comment]
@trz42 I feel the changes here are trivial enough to include them in the `v0.1.0` release of the bot, but I'll let you be the judge of that...

**Comment by trz42** [comment]
> @trz42 I feel the changes here are trivial enough to include them in the `v0.1.0` release of the bot, but I'll let you be the judge of that...

Not fully clear to me what the tests in https://github.com/EESSI/software-layer/pull/337 and https://github.com/boegel/software-layer/pull/27 show ... there is very little information about what has been tested (e.g., a successful download and then the reuse of the downloaded sources; how does this improve the _fluke_ download issue if the first download for the $N-1$-th dependency fails?). Are the tests sufficient to demonstrate that this PR solves the issue (https://github.com/EESSI/eessi-bot-software-layer/issues/213) and what undesired consequences may they have (multiple jobs writing concurrently to the shared directory or worse the same files ...).

To me this looks more like a performance optimisation (avoiding repeated downloads of the same sources), than solving the _fluke_ download issue.

**Comment by boegel** [comment]
You're right about the concurrent downloads to a shared place. The idea is to combine setting `shared_fs_path` with starting only a single build job per PR initially, which takes care of the downloading.
EasyBuild currently doesn't use a lock when a download is being done, but it could, and if a 2nd download waits for a while until the download lock is released, that would prevent problems with concurrent downloads.

It doesn't fully avoid the download fluke problem, so I wouldn't close https://github.com/EESSI/eessi-bot-software-layer/issues/213 just yet, but it should make it as lot less likely since every file only needs to be downloaded once.
I'm not sure we can fully avoid download problems btw, we're always at the mercy of whatever site provides the source tarballs?

Keep in mind that the same source tarball can be used for other PRs as well, like `zlib` 1.2.13 for example.
Right now source tarballs are *always* downloaded in a build job, there's no caching of downloads at all.

**Review by trz42 — APPROVED** [review]
Looks good. Should be fine.

**Pull request merged**
